### PR TITLE
Add jwt token in session and validate from there

### PR DESCRIPTION
**Pull request by grimpy**
Fix issue where cockpit client uses a global client not specific to
user of the request.
Store jwttoken on the user session and validate from there.

### CODE REVIEW

**Comment by grimpy** [comment]
@xmonader can you test this PR? I hope this fixes some of the jwt mess.

**Comment by zaibon** [comment]
Looks good to me. I can merge after test is done.

**Comment by xmonader** [comment]
Works for me.

**Comment by zaibon** [comment]
I switch my cockpit to this branch to test. I'll re-test tomorrow cause the error occurs after the JWT has expired so after 24h. If tomorrow still no error I'll merge

**Comment by grimpy** [comment]
@zaibon even if it doesnt fix the jwt expired issue you should still merge it cause if fixes a global state issue.

**Pull request merged**
